### PR TITLE
To replace smooth scroll with Lenis

### PR DESCRIPTION
**Pull request by clementroche**
This PR replace smooth scroll with Lenis and add docs for dev purpose. I left the old script commented in case i forgot some features. We can clean later if PR is accepted.

Breaking change: page doens't require a scroll container anymore, the `data-lg-smooth` has to be added to `html` element instead.

### CODE REVIEW

**Comment by nicholasruggeri** [comment]
Any change to get Lenis in the final release?

**Comment by AntoineW** [comment]
Hello,
Unfortunately no, I'm not too sure about the way lenis handles scroll using a duration and easing function. I'm working on revamped version of luge SmoothScroll to integrate a simpler solution using a similar approach.

Though, would you be interested in using both luge and lenis?

**Comment by nicholasruggeri** [comment]
@AntoineW Yes, I'd like to use both. I think it's a good combo.

**Comment by AntoineW** [comment]
The smooth scroll has been updated to use window.scrollTo + virtual scroll technique.

**Pull request closed without merging**
